general.import = [
  "./catppuccin-mocha.toml"
]

[font]
normal = { family = "Cozette" }

[window]
# opacity = 0.5

[scrolling]
# history = 0

[cursor]
style = { shape = "Beam", blinking = "Always" }
vi_mode_style  = { shape = "Block" }
blink_interval = 500
blink_timeout = 0
