#!/usr/bin/env sh

alias \
  ls="eza --icons --git --group-directories-first" \
  ll="ls -l" \
  la="ll -a" \
  tree="ls --tree --level=3" \
  grep="grep --color=auto" \
  cp="cp --interactive" \
  mv="mv --interactive" \
  rm="rm --interactive" \
  ..="cd .." \
  ...="cd ../.." \
  ....="cd ../../.." \
  cat="bat -pp" \
  bc="bc-gh" \
  dc="dc-gh" \
  vim="$EDITOR" \
  wget="wcurl" \
  cls="clear" \
  rompatcher="rom-patcher"
